services:
  web:
    image: nginx
    ports:
      - "81:80"
    restart: always
    volumes:
      - /users/svetlana/projects/test/online-shop/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /users/svetlana/projects/test/online-shop:/var/www/html
    depends_on:
      - php-fpm
      - db


  php-fpm:
    build: ./docker/php
    restart: always
    volumes:
      - /users/svetlana/projects/test/online-shop:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-xdebug.ini

  db:
    image: postgres:13
    restart: always
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 54324:5432









