services:
  web:
    image: nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - /users/svetlana/projects/environment1/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /users/svetlana/projects/environment1:/var/www/html
    depends_on:
      - php-fpm
      - db


  php-fpm:
    build: ./docker/php
    restart: always
    volumes:
      - /users/svetlana/projects/environment1:/var/www/html

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432








